# Generated by Django 5.0.6 on 2024-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'db_table': 'voice',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название русское')),
                ('title_latin', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Название латинское')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('season', models.CharField(choices=[('summer', 'лето'), ('autumn', 'осень'), ('spring', 'весна'), ('winter', 'зима')], max_length=6, verbose_name='Сезон')),
                ('status', models.CharField(choices=[('ongoing', 'онгоинг'), ('completed', 'завершен'), ('announcement', 'анонс')], max_length=12, verbose_name='Статус')),
                ('new_episode_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата нового эпизода')),
                ('new_episode_every', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=12, verbose_name='Новый эпизод каждую')),
                ('episodes_number', models.PositiveIntegerField(default=0, verbose_name='Количество эпизодов')),
                ('cover_image', models.ImageField(upload_to='covers', verbose_name='Обложка')),
                ('genres', models.ManyToManyField(related_name='animes', to='anime.genre', verbose_name='Жанры')),
                ('voices', models.ManyToManyField(related_name='animes', to='anime.voice', verbose_name='Озвучки')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'db_table': 'anime',
            },
        ),
    ]
