# Generated by Django 5.0.6 on 2024-07-12 14:05

import anime.models.episode_model
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название [русское]')),
                ('title_latin', models.CharField(max_length=200, unique=True, verbose_name='Название [латинское]')),
                ('slug', models.SlugField(max_length=250, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('season', models.CharField(choices=[('summer', 'лето'), ('autumn', 'осень'), ('spring', 'весна'), ('winter', 'зима')], max_length=6, verbose_name='Сезон')),
                ('status', models.CharField(choices=[('ongoing', 'онгоинг'), ('completed', 'завершен'), ('announcement', 'анонс')], max_length=12, verbose_name='Статус озвучки')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Количество в любимых')),
                ('new_episode_every', models.CharField(blank=True, choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=11, null=True, verbose_name='Новый эпизод еженедельно')),
                ('episodes_number', models.PositiveSmallIntegerField(default=0, verbose_name='Количество серии')),
                ('image', models.ImageField(upload_to='anime_covers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg'])], verbose_name='Постер')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'db_table': 'anime',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Субтитры')),
            ],
            options={
                'verbose_name': 'Субтитры',
                'verbose_name_plural': 'Субтитры',
                'db_table': 'subtitles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тайминг')),
            ],
            options={
                'verbose_name': 'Тайминг',
                'verbose_name_plural': 'Тайминги',
                'db_table': 'timing',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Голос')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'db_table': 'voice',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.SmallIntegerField(verbose_name='Номер эпизода')),
                ('video', models.FileField(upload_to=anime.models.episode_model.episode_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Видео')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'db_table': 'episode',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='anime_list', to='anime.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='anime',
            name='subtitles',
            field=models.ManyToManyField(related_name='anime_list', to='anime.subtitles', verbose_name='Субтитры'),
        ),
        migrations.AddField(
            model_name='anime',
            name='timing',
            field=models.ManyToManyField(related_name='anime_list', to='anime.timing', verbose_name='Тайминг'),
        ),
        migrations.AddField(
            model_name='anime',
            name='voices',
            field=models.ManyToManyField(related_name='anime_list', to='anime.voice', verbose_name='Голоса'),
        ),
    ]
