# Generated by Django 5.0.6 on 2024-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_new_episode_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество в избранных'),
        ),
    ]
