# Generated by Django 5.0.6 on 2024-06-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_favorites_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voice',
            options={'ordering': ['name'], 'verbose_name': 'Озвучка', 'verbose_name_plural': 'Озвучки'},
        ),
    ]
