# Generated by Django 5.0.6 on 2024-06-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_voice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['title'], 'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
