# Generated by Django 5.0.6 on 2024-06-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_options_alter_genre_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='new_episode_date',
        ),
        migrations.AddField(
            model_name='anime',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
